version: '3.8'

services:
  # wireguard:
  #   image: linuxserver/wireguard:amd64-latest
  #   hostname: wireguard
  #   container_name: wireguard
  #   cap_add:
  #     - NET_ADMIN
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=America/New_York
  #   sysctls:
  #     - net.ipv4.conf.all.src_valid_mark=1
  #     - net.ipv4.ip_forward=1
  #     - net.ipv6.conf.all.disable_ipv6=0
  #   volumes:
  #     - ./wg0.conf:/config/wg_confs/wg0.conf
  #     - /lib/modules:/lib/modules
  #   restart: always

  socat:
    image: bennythink/socat
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: [ "socat", "tcp-listen:2375,fork,reuseaddr","unix-connect:/var/run/docker.sock" ]

  redis:
    image: redis:7-alpine
    restart: always
    logging:
      driver: none

  mysql:
    image: ubuntu/mysql:8.0-22.04_beta
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    command: --default-authentication-plugin=mysql_native_password
    logging:
      driver: none

  ytdl:
    image: fieron/ytdlbot
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/ytdl.env
    restart: always
    # network_mode: service:wireguard
    depends_on:
      - socat
      - redis
      # - wireguard
    volumes:
      - ./data/vnstat/:/var/lib/vnstat/
      - sessions:/var/sessions
      - ./texts:/ytdlbot/texts
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  sessions: